export const photoConstants = {
  UPDATE_SUCCESS: "PHOTO_UPDATE_SUCCESS",
  UPDATE_FAILURE: "PHOTO_UPDATE_FAILURE",
  SEARCH_SUCCESS: "PHOTO_SEARCH_SUCCESS",
  SEARCH_FAILURE: "PHOTO_SEARCH_FAILURE"
};
